--
-- Tabellenstruktur für Tabelle `uw3ro_energies`
--

CREATE TABLE IF NOT EXISTS `#__energies` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `cid` int(11) NOT NULL DEFAULT 0,
    `name` varchar(255) NOT NULL DEFAULT '',
    `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    `state` tinyint(3) NOT NULL DEFAULT 0,
    `catid` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `description` mediumtext NOT NULL,
    `color` varchar(7) NOT NULL DEFAULT '#999999',
    `weight` int(2) NOT NULL DEFAULT 2 COMMENT 'Die dicke der Linie in der Graphanzeige',
    `dbdb` int(11) DEFAULT 0 COMMENT 'Datenbank der Daten',
    `tablename` varchar(40) DEFAULT NULL COMMENT 'Tabellennamen der Daten',
    `datefield` varchar(40) DEFAULT 'datum' COMMENT 'Tabellenspalte mit Date-Time Wert',
    `datafield` varchar(40) NOT NULL DEFAULT 'verbrauch' COMMENT 'Tabellenspalte mit Verbrauchswert',
    `triggerfield` varchar(40) NOT NULL DEFAULT '-1' COMMENT 'Triggerfeldangabe für Triggerauswertung',
    `dateformat` varchar(15) NOT NULL COMMENT 'Legt das Format der Y-Beschriftung des Grafen fest',
    `auswertung` tinyint(3) NOT NULL DEFAULT 0,
    `sticky` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
    `ordering` int(11) NOT NULL DEFAULT 0,
    `metakey` mediumtext NOT NULL,
    `params` mediumtext NOT NULL,
    `checked_out` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `created_by` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `created_by_alias` varchar(255) NOT NULL DEFAULT '',
    `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `modified_by` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `version` int(10) UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`),
    KEY `idx_state` (`state`),
    KEY `idx_banner_catid` (`catid`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Tabellenstruktur für Tabelle `uw3ro_energies_db`
--

CREATE TABLE IF NOT EXISTS `#__energies_db` (
    `id` int(11) NOT NULL AUTO_INCREMENT,
    `cid` int(11) NOT NULL DEFAULT 0,
    `name` varchar(255) NOT NULL DEFAULT '',
    `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    `state` tinyint(3) NOT NULL DEFAULT 0,
    `catid` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `description` mediumtext NOT NULL,
    `datenbasis` tinyint(3) NOT NULL DEFAULT 0,
    `dbdriver` varchar(100) DEFAULT NULL COMMENT 'Treiber der Datenbank',
    `dbhost` varchar(100) DEFAULT NULL COMMENT 'Der Host der Datenbank',
    `dbdb` varchar(100) DEFAULT NULL COMMENT 'Der Name der Datenbank',
    `dbuser` varchar(40) DEFAULT NULL COMMENT 'Benutzername der Datenbank',
    `dbpass` varchar(100) DEFAULT NULL COMMENT 'Das Passwort für den Datenbankzugriff',
    `dbprefix` varchar(30) DEFAULT NULL COMMENT 'Der Prefix vor dem eigentlichen Tabellennamen',
    `ftphost` varchar(100) DEFAULT NULL,
    `ftpuser` varchar(40) DEFAULT NULL,
    `ftppass` varchar(100) DEFAULT NULL,
    `ftpdir` varchar(100) DEFAULT NULL,
    `ftpprefix` varchar(30) DEFAULT NULL,
    `ftptrennz` varchar(2) DEFAULT NULL,
    `ftperstez` tinyint(1) DEFAULT NULL,
    `ftpzeilenlaenge` int(11) DEFAULT NULL,
    `ftpintervall` tinyint(3) DEFAULT 0,
    `sticky` tinyint(1) UNSIGNED NOT NULL DEFAULT 0,
    `ordering` int(11) NOT NULL DEFAULT 0,
    `metakey` mediumtext NOT NULL,
    `params` mediumtext NOT NULL,
    `checked_out` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `created_by` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `created_by_alias` varchar(255) NOT NULL DEFAULT '',
    `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `modified_by` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `version` int(10) UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`),
    KEY `idx_state` (`state`),
    KEY `idx_banner_catid` (`catid`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;