--
-- Tabellenstruktur für Tabelle `#__tagebuch`
--

CREATE TABLE IF NOT EXISTS `#__tagebuch` (
    `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'id des eintrages',
    `alias` varchar(255) NOT NULL DEFAULT '',
    `sff` int(11) UNSIGNED DEFAULT NULL COMMENT 'Schichtführer Frühschicht',
    `sfs` int(11) UNSIGNED DEFAULT NULL COMMENT 'Schichtführer Spätschicht',
    `sfan` int(11) UNSIGNED DEFAULT NULL,
    `text_fs` mediumtext DEFAULT NULL,
    `text_ss` mediumtext DEFAULT NULL,
    `text_z1` mediumtext DEFAULT NULL,
    `text_z2` mediumtext DEFAULT NULL,
    `text_an` mediumtext CHARACTER SET utf8mb4 DEFAULT NULL,
    `text_bl` mediumtext DEFAULT NULL,
    `datum` datetime DEFAULT NULL,
    `fs_erstellt` datetime DEFAULT NULL,
    `fs_erstellt_von` int(11) DEFAULT NULL,
    `fs_laenderung` datetime DEFAULT NULL,
    `fs_laenderung_von` int(11) UNSIGNED DEFAULT NULL,
    `ss_erstellt` datetime DEFAULT NULL,
    `ss_erstellt_von` int(11) UNSIGNED DEFAULT NULL,
    `ss_laenderung` datetime DEFAULT NULL,
    `ss_laenderung_von` int(11) UNSIGNED DEFAULT NULL,
    `z1_erstellt` datetime DEFAULT NULL,
    `z1_erstellt_von` int(11) UNSIGNED DEFAULT NULL,
    `z1_laenderung` datetime DEFAULT NULL,
    `z1_laenderung_von` int(11) UNSIGNED DEFAULT NULL,
    `z2_erstellt` datetime DEFAULT NULL,
    `z2_erstellt_von` int(11) UNSIGNED DEFAULT NULL,
    `z2_laenderung` datetime DEFAULT NULL,
    `z2_laenderung_von` int(11) UNSIGNED DEFAULT NULL,
    `an_erstellt` datetime DEFAULT NULL,
    `an_erstellt_von` int(11) UNSIGNED DEFAULT NULL,
    `an_laenderung` datetime DEFAULT NULL,
    `an_laenderung_von` int(11) UNSIGNED DEFAULT NULL,
    `bl_erstellt` datetime DEFAULT NULL,
    `bl_erstellt_von` int(11) UNSIGNED DEFAULT NULL,
    `bl_laenderung` datetime DEFAULT NULL,
    `bl_laenderung_von` int(11) UNSIGNED DEFAULT NULL,
    `bereich_fahrzeug1` int(11) UNSIGNED DEFAULT NULL,
    `bereich_fahrzeug2` int(11) UNSIGNED DEFAULT NULL,
    `bereich_fahrzeug3` int(11) UNSIGNED DEFAULT NULL,
    `bereich_fahrzeug4` int(11) UNSIGNED DEFAULT NULL,
    `state` tinyint(1) NOT NULL DEFAULT 0,
    `checked_out` int(11) UNSIGNED NOT NULL DEFAULT 0,
    `checked_out_time` datetime DEFAULT NULL,
    `access` int(11) NOT NULL DEFAULT 1,
    `gesehen` tinyint(1) NOT NULL DEFAULT 0,
    `abluft_ok` tinyint(1) NOT NULL DEFAULT 0,
    `metakey` text NOT NULL,
    `metadesc` text NOT NULL,
    `metadata` text NOT NULL,
    `publish_up` datetime NOT NULL,
    `attribs` varchar(5120) DEFAULT NULL,
    `publish_down` datetime NOT NULL,
    `modified` datetime NOT NULL,
    `modified_by` int(10) NOT NULL,
    `version` int(10) NOT NULL DEFAULT 1,
    `note` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `datum` (`datum`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;

--
-- Tabellenstruktur für Tabelle `#__tagebuch_avv`
--

CREATE TABLE IF NOT EXISTS `#__tagebuch_avv` (
    `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `lfdnr` varchar(10) NOT NULL,
    `sortennr` int(11) DEFAULT NULL COMMENT 'Die Sortennummer aus E-Max',
    `title` varchar(250) NOT NULL,
    `alias` varchar(400) NOT NULL,
    `ueberschrift` tinyint(1) NOT NULL DEFAULT 0,
    `avv` varchar(15) DEFAULT NULL,
    `avvname` varchar(255) DEFAULT NULL,
    `catid` int(11) NOT NULL DEFAULT 0,
    `description` mediumtext NOT NULL,
    `einheit` varchar(5) DEFAULT NULL,
    `state` tinyint(1) NOT NULL DEFAULT 0,
    `checked_out` int(11) NOT NULL DEFAULT 0,
    `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `ordering` int(11) NOT NULL DEFAULT 0,
    `access` int(11) NOT NULL DEFAULT 1,
    `attribs` varchar(5120) DEFAULT NULL,
    `metakey` mediumtext NOT NULL,
    `metadesc` mediumtext NOT NULL,
    `metadata` mediumtext NOT NULL,
    `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `created_by` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `created_by_alias` varchar(255) NOT NULL DEFAULT '',
    `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `modified_by` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `version` int(10) UNSIGNED NOT NULL DEFAULT 1,
    `note` varchar(255) DEFAULT NULL,
    PRIMARY KEY (`id`),
    KEY `idx_access` (`access`),
    KEY `idx_checkout` (`checked_out`),
    KEY `idx_state` (`state`),
    KEY `idx_catid` (`catid`),
    KEY `idx_createdby` (`created_by`),
    KEY `idx_featured_catid` (`catid`),
    KEY `lfdnr` (`lfdnr`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Tabellenstruktur für Tabelle `#__tagebuch_masch`
--

CREATE TABLE IF NOT EXISTS `#__tagebuch_masch` (
    `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
    `wid` int(11) UNSIGNED NOT NULL COMMENT 'Verknüpfung zu Wartung ID',
    `title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `state` tinyint(3) NOT NULL DEFAULT 0,
    `params` text DEFAULT NULL,
    `version` int(10) UNSIGNED NOT NULL DEFAULT 1,
    `catid` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `created_by` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `created_by_alias` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
    `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `modified_by` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `checked_out` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `ordering` int(11) NOT NULL DEFAULT 0,
    `metakey` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `metadesc` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    `access` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `metadata` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
    PRIMARY KEY (`id`),
    KEY `wid` (`wid`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;