--
-- Tabellenstruktur für Tabelle `uw3ro_cbks`
--

CREATE TABLE IF NOT EXISTS `#__cbks` (
    `id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `mid` int(11) NOT NULL COMMENT 'Link zur Mietenid',
    `kwin` varchar(6)  DEFAULT NULL COMMENT 'KW Eintrag',
    `kwout` varchar(6) DEFAULT NULL COMMENT 'KW Austrag',
    `starteintrag` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
    `endeaustrag` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
    `EintragBio` varchar(10) DEFAULT NULL,
    `EintragStrukt` varchar(10) DEFAULT NULL,
    `Rottegrad` tinyint(2) DEFAULT NULL,
    `AustragFein` varchar(10) DEFAULT NULL,
    `AustragRest` varchar(10) DEFAULT NULL,
    `mietebeendet` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'Wird "True" wenn die Miete vollständig ausgetragen wurde',
    `catid` int(11) NOT NULL DEFAULT 0,
    `title` varchar(250) NOT NULL DEFAULT '',
    `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL DEFAULT '',
    `description` mediumtext NOT NULL,
    `state` tinyint(1) NOT NULL DEFAULT 0,
    `checked_out` int(11) NOT NULL DEFAULT 0,
    `checked_out_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `ordering` int(11) NOT NULL DEFAULT 0,
    `access` int(11) NOT NULL DEFAULT 1,
    `params` mediumtext NOT NULL,
    `created` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `created_by` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `created_by_alias` varchar(255) NOT NULL DEFAULT '',
    `modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `modified_by` int(10) UNSIGNED NOT NULL DEFAULT 0,
    `publish_up` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `publish_down` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
    `version` int(10) UNSIGNED NOT NULL DEFAULT 1,
    PRIMARY KEY (`id`),
    UNIQUE KEY `Mieten ID` (`mid`),
    KEY `idx_access` (`access`),
    KEY `idx_checkout` (`checked_out`),
    KEY `idx_state` (`state`),
    KEY `idx_catid` (`catid`),
    KEY `idx_createdby` (`created_by`),
    KEY `idx_featured_catid` (`catid`)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;